trigger: none

parameters:
  - name: environments
    type: object
    default: 
      - region: "USC"
        environment:
          - 'DEV'
          - 'QA'

stages:
  - stage: Build
    displayName: Build stage
    variables:
      - template: "${{variables.System.ArtifactsDirectory}}/variables/manifest-flask.yml"
    jobs:
      - job: BuildJob
        pool: 
          vmimage: "ubuntu-latest"
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python $(pythonVersion)'
  
          - script: |
              python -m venv antenv
              source antenv/bin/activate
              python -m pip install --upgrade pip
              pip install setup
              pip install -r requirements.txt
            workingDirectory: $(System.DefaultWorkingDirectory)
            displayName: "Install requirements"
  
          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true
  
          - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            displayName: 'Upload package'
            artifact: drop

  - ${{ each e in parameters.region }}:
    - ${{ each env in e.environment }}:
      - stage: "${{ env }}"
        displayName: "Deploy Web App on ${{ env }} Environment"
        ${{ if eq(env, 'dev') }}:
          dependsOn: [Build]
          condition: succeeded()
        ${{ if eq(env,'qa') }}:
          dependsOn: [Build,Dev]
          condition: succeeded()
        jobs:
          - deployment: DeploymentJob
            pool: "Self-Hosted-Agent"
            environment: Development
            variables:
              - template: "${{variables.System.ArtifactsDirectory}}/variables/manifest-flask-${{ e.env }}.yml"
            strategy:
              runOnce:
                deploy:
                  steps:
                  - template: "${{variables.system.ArtifactsDirectory}}/templates/webAppDeploy.yml"
                    parameters: 
                      azureConnection: ${{variables.azureConnection}}
                      webAppName: ${{variables.webAppName}}