# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

variables:
  - template: "${{variables.System.ArtifactsDirectory}}/variables/manifest-flask.yml"

#  # Azure Resource Manager connection created during pipeline creation
#  azureServiceConnectionId: 'b9402fe9-12a9-4327-916e-a189359239e5'
#
#  # Web app name
#  webAppName: 'USCentralDevCICDLabWebApp01'
#  
#  #Resource group name
#  resourceGroupName: 'USCentralDevCICDLab'
#
#  # Agent VM image name
#  vmImageName: 'ubuntu-latest'
#
#  # Environment name
#  environmentName: 'USCentralDevCICDLabWebApp01'
#
#  # Project root folder. Point to the folder containing manage.py file.
#  projectRoot: $(System.DefaultWorkingDirectory)
#
#  # Python version: 3.7
#  pythonVersion: '3.7'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool: "Linux-Self-Hosted-Agent"
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    - script: |
        python -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install setup
        pip install -r requirements.txt
      workingDirectory: $(System.DefaultWorkingDirectory)
      displayName: "Install requirements"

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool: "Linux-Self-Hosted-Agent"
    environment: Development
    strategy:
      runOnce:
        deploy:
          steps:

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python version'

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : $(webAppName)'
            inputs:
              azureSubscription: $(azureConnection)
              appName: $(webAppName)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
          
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureConnection)
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: 'az webapp config set --resource-group $(resourceGroupName) --name $(webAppName) --startup-file "startup.txt"'
